version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=thaothao
      - POSTGRES_USER=thaovu
      - POSTGRES_PASSWORD=thaothao2022
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=thaothao
      - POSTGRES_USER=thaovu
      - POSTGRES_PASSWORD=thaothao2022
    depends_on:
      - db